name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Trigger on 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (use Node.js 18 to fix crypto.getRandomValues error)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the React app
      - name: Build React app
        run: npm run build

      # ✅ Debug: Check if ./build exists
      - name: Debug - List files
        run: ls -la

      # Deploy to InfinityFree via FTP
      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/  # Ensure trailing slash
          server-dir: /htdocs/  # Ensure correct InfinityFree directory
